apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: github-tests-java-quarkus-eilprqha
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap-test-organization-jk/github-tests-java-quarkus-eilprqha:jenkins-d52e1fd3e5295b41ce5a8f36d01b72f99454ea4b
          name: container-image
